# Generated by Django 4.2.26 on 2025-11-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigIntegerField(help_text='从LDAP cn字段同步，外部系统提供的部门ID', primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(help_text='从LDAP ou字段同步的部门名称', max_length=200, verbose_name='部门名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, help_text='LDAP employeeNumber 字段', max_length=50, verbose_name='员工编号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, help_text='关联到部门表，从LDAP departmentNumber字段同步', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='account.department', verbose_name='所属部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_profile',
                'indexes': [models.Index(fields=['employee_number'], name='user_profil_employe_211fd0_idx'), models.Index(fields=['department'], name='user_profil_departm_81761c_idx')],
            },
        ),
    ]
