# Generated by Django 4.2.26 on 2025-11-08 15:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVPNAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikuai_id', models.IntegerField(blank=True, help_text='iKuai系统返回的账号ID', null=True, unique=True, verbose_name='iKuai账号ID')),
                ('username', models.CharField(help_text='OpenVPN登录用户名', max_length=100, unique=True, verbose_name='VPN账号')),
                ('password', models.CharField(help_text='OpenVPN登录密码', max_length=100, verbose_name='VPN密码')),
                ('status', models.CharField(choices=[('creating', '创建中'), ('active', '正常'), ('expired', '已过期'), ('disabled', '已禁用'), ('failed', '创建失败')], db_index=True, default='creating', max_length=20, verbose_name='账号状态')),
                ('enabled', models.BooleanField(default=True, help_text='对应iKuai的enabled字段', verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, help_text='账号生效时间', null=True, verbose_name='开始时间')),
                ('expires', models.DateTimeField(blank=True, db_index=True, help_text='账号到期时间', null=True, verbose_name='过期时间')),
                ('last_conntime', models.DateTimeField(blank=True, help_text='最后一次连接VPN的时间', null=True, verbose_name='最后连接时间')),
                ('last_offtime', models.DateTimeField(blank=True, help_text='最后一次断开连接的时间', null=True, verbose_name='最后离线时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, help_text='分配的VPN IP地址', null=True, verbose_name='IP地址')),
                ('ip_type', models.IntegerField(default=0, help_text='0=自动分配', verbose_name='IP类型')),
                ('mac', models.CharField(blank=True, default='', max_length=17, verbose_name='MAC地址')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('comment', models.TextField(blank=True, default='', verbose_name='备注')),
                ('ppptype', models.CharField(default='any', max_length=20, verbose_name='PPP类型')),
                ('pppname', models.CharField(blank=True, default='', max_length=50, verbose_name='PPP名称')),
                ('bind_ifname', models.CharField(default='any', max_length=50, verbose_name='绑定接口')),
                ('bind_vlanid', models.CharField(default='0', max_length=20, verbose_name='绑定VLAN ID')),
                ('auto_vlanid', models.IntegerField(default=1, verbose_name='自动VLAN')),
                ('share', models.IntegerField(default=1, help_text='允许的最大并发连接数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='共享连接数')),
                ('upload', models.BigIntegerField(default=0, help_text='上传速度限制(KB/s)，0为不限速', verbose_name='上传限速')),
                ('download', models.BigIntegerField(default=0, help_text='下载速度限制(KB/s)，0为不限速', verbose_name='下载限速')),
                ('duration', models.IntegerField(default=0, help_text='累计在线时长(秒)', verbose_name='在线时长')),
                ('packages', models.BigIntegerField(default=0, help_text='流量包大小(字节)', verbose_name='流量包')),
                ('cardid', models.CharField(blank=True, default='', max_length=100, verbose_name='卡号')),
                ('auto_mac', models.IntegerField(default=1, verbose_name='自动MAC')),
                ('task_id', models.CharField(blank=True, default='', help_text='创建账号的Celery任务ID', max_length=100, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, default='', help_text='创建失败时的错误信息', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openvpn_account', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': 'OpenVPN账号',
                'verbose_name_plural': 'OpenVPN账号',
                'db_table': 'openvpn_account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='openvpn_acc_status_1c5771_idx'), models.Index(fields=['expires'], name='openvpn_acc_expires_958e82_idx'), models.Index(fields=['username'], name='openvpn_acc_usernam_8be77c_idx')],
            },
        ),
    ]
